apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-00
  namespace: cacppt-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: cluster-00-controlplane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPCluster
    name: cluster-00
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPCluster
metadata:
  name: cluster-00
  namespace: cacppt-system
spec:
  network:
    name: default
  project: rising-capsule-353505
  region: us-central1
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: cluster-00-controlplane
  namespace: cacppt-system
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.0.6
    init:
      configPatches:
      - op: replace
        path: /cluster/proxy/disabled
        value: true
      - op: replace
        path: /cluster/network/cni
        value:
          name: none
      generateType: init
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPMachineTemplate
    name: cluster-00-controlplane
  replicas: 1
  version: v1.23.7
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: cluster-00-controlplane
  namespace: cacppt-system
spec:
  template:
    spec:
      image: projects/rising-capsule-353505/global/images/talos-v1-0-6
      instanceType: n1-standard-2
      publicIP: true
      rootDeviceSize: 50
      serviceAccounts:
        email: cluster-api@rising-capsule-353505.iam.gserviceaccount.com
        scopes:
        - https://www.googleapis.com/auth/compute
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: cluster-00
    nodepool: nodepool-a
  name: cluster-00-workers
  namespace: cacppt-system
spec:
  clusterName: cluster-00
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: cluster-00
      nodepool: nodepool-a
  strategy:
    rollingUpdate:
      deletePolicy: Oldest
      maxSurge: 10%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: cluster-00
        nodepool: nodepool-a
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: cluster-00-workers
      clusterName: cluster-00
      failureDomain: us-central1-a
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPMachineTemplate
        name: cluster-00-workers
      version: 1.23.7
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: cluster-00-workers
  namespace: cacppt-system
spec:
  template:
    spec:
      image: projects/rising-capsule-353505/global/images/talos-v1-0-6
      instanceType: n1-standard-2
      publicIP: true
      rootDeviceSize: 50
      serviceAccounts:
        email: cluster-api@rising-capsule-353505.iam.gserviceaccount.com
        scopes:
        - https://www.googleapis.com/auth/compute
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: cluster-00-workers
  namespace: cacppt-system
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.0.6
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachineHealthCheck
metadata:
  name: cluster-00-worker-hc
  namespace: cacppt-system
spec:
  clusterName: cluster-00
  maxUnhealthy: 40%
  nodeStartupTimeout: 20m
  selector:
    matchLabels:
      nodepool: nodepool-a
  unhealthyConditions:
  - status: Unknown
    timeout: 300s
    type: Ready
  - status: "False"
    timeout: 300s
    type: Ready
